-- DEMO SEED · generado desde core/model.js · BORRAR antes de importar Excel reales
-- Reinicio limpio (las tablas hijas van primero por las FKs)
DELETE FROM partos;
DELETE FROM tratamientos;
DELETE FROM produccion_mensual;
DELETE FROM ordenos;
DELETE FROM palpaciones;
DELETE FROM movimientos_potrero;
DELETE FROM animales;
DELETE FROM lecheros;
DELETE FROM potreros;

-- ANIMALES
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('042', 'Lucero', 'Holstein × Gyr', 'ordeño', 'H', 5.2, 'nacido_finca', 152, 3, 18, 'prenada', 6, '2026-09-12', '2026-05-02', NULL, NULL, '2026-07-12', NULL, 480, '2026-04-15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('038', 'Mona', 'Gyrolando', 'ordeño', 'H', 4.1, 'nacido_finca', 98, 2, 16, 'servida', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 460, '2026-04-15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('051', 'Careta', 'Holstein × Gyr', 'ordeño', 'H', 3.2, 'nacido_finca', 121, 1, 14, 'vacia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 420, '2026-03-15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('027', 'Estrella', 'Gyrolando', 'ordeño', 'H', 3.8, 'nacido_finca', 64, 1, 13, 'vacia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 440, '2026-05-15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('017', 'Azucena', 'Holstein', 'ordeño', 'H', 8, 'nacido_finca', 201, 5, 11, 'prenada', 4, NULL, '2026-05-01', NULL, NULL, NULL, '2026-06-14', 510, '2026-04-15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('033', 'Paloma', 'Normando', 'ordeño', 'H', 6.5, 'nacido_finca', 95, 4, 6, 'vacia', NULL, NULL, '2026-02-03', 132, NULL, NULL, NULL, 490, '2026-05-15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('029', 'Pinta', 'Holstein × Gyr', 'ordeño', 'H', 7, 'comprado', 412, 5, 5, 'vacia', NULL, NULL, '2026-01-18', 150, NULL, NULL, NULL, 470, '2026-05-15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('015', 'Mariposa', 'Gyrolando', 'ordeño', 'H', 5, NULL, 180, 3, 10, 'prenada', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('023', 'Candelaria', 'Holstein', 'ordeño', 'H', 6, NULL, 142, 4, 12, 'prenada', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('035', 'Rocío', 'Normando', 'ordeño', 'H', 4.5, NULL, 110, 2, 14, 'prenada', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('040', 'Nieve', 'Holstein × Gyr', 'ordeño', 'H', 3.5, NULL, 88, 1, 15, 'prenada', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('046', 'Esperanza', 'Gyrolando', 'ordeño', 'H', 5.8, NULL, 195, 3, 9, 'prenada', 7, NULL, NULL, NULL, NULL, '2026-07-31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('011', 'Violeta', 'Gyrolando', 'horra', 'H', 7, NULL, NULL, 0, NULL, 'prenada', 8.5, '2026-07-03', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('019', 'Canela', 'Holstein × Gyr', 'horra', 'H', 6, NULL, NULL, 0, NULL, 'prenada', 8, '2026-07-18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('045', 'Morena', 'Normando', 'horra', 'H', 5.5, NULL, NULL, 0, NULL, 'prenada', 7.5, '2026-08-02', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('008', 'Golondrina', 'Holstein', 'horra', 'H', 9, NULL, NULL, 0, NULL, 'prenada', 7, '2026-09-12', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('036', 'Cereza', 'Gyrolando', 'horra', 'H', 4, NULL, NULL, 0, NULL, 'prenada', 7, '2026-09-15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('041', 'Garza', 'Holstein × Gyr', 'horra', 'H', 5.2, NULL, NULL, 0, NULL, 'prenada', 6.5, '2026-09-28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('014', 'Nube', 'Gyrolando', 'horra', 'H', 6.8, NULL, NULL, 0, NULL, 'prenada', 6, '2026-10-10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('048', 'Flor', 'Normando', 'horra', 'H', 3.8, NULL, NULL, 0, NULL, 'prenada', 5.5, '2026-10-25', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('022', 'Luna', 'Holstein', 'horra', 'H', 7.5, NULL, NULL, 0, NULL, 'prenada', 5, '2026-11-08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('055', 'Princesa', 'Gyrolando', 'novilla', 'H', 2.1, NULL, NULL, 0, NULL, 'novilla', NULL, NULL, NULL, NULL, TRUE, NULL, NULL, 342, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('058', 'Alondra', 'Holstein × Gyr', 'novilla', 'H', 2, NULL, NULL, 0, NULL, 'novilla', NULL, NULL, NULL, NULL, TRUE, NULL, NULL, 335, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('061', 'Café', 'Normando', 'novilla', 'H', 1.9, NULL, NULL, 0, NULL, 'novilla', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, 318, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('063', 'Dalia', 'Gyrolando', 'novilla', 'H', 1.7, NULL, NULL, 0, NULL, 'novilla', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, 295, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('067', 'Sirena', 'Holstein', 'novilla', 'H', 1.5, NULL, NULL, 0, NULL, 'novilla', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, 275, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('066', 'Esmeralda', 'Gyrolando', 'levante', 'H', 1.17, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 218, NULL, 480, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('068', 'Perla', 'Holstein × Gyr', 'levante', 'H', 1.08, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 201, NULL, 470, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('070', 'Coral', 'Normando', 'levante', 'H', 0.92, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 178, NULL, 490, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('064', 'Cría de Lucero', 'Holstein × Gyr', 'ternera', 'H', 0.42, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('069', 'Cría de Estrella', 'Gyrolando', 'ternera', 'H', 0.29, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('071', 'Cría de Canela', 'Holstein × Gyr', 'ternera', 'H', 0.38, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('073', 'Cría de Morena', 'Normando', 'ternera', 'H', 0.25, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('T01', 'Sansón', 'Gyr', 'macho', 'M', 6, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, TRUE, 23, TRUE, NULL, NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('T02', 'Torete', 'Gyr', 'macho', 'M', 0.92, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-08-01', NULL, NULL, NULL, NULL);
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('021', 'Lucía', 'Holstein × Gyr', 'baja', 'H', 8, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'venta', '2026-05-04', 2100000, 'descarte por baja producción');
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('009', 'Manzana', 'Gyrolando', 'baja', 'H', 7, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'muerte', '2026-04-18', 0, 'timpanismo');
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('044', 'Estrella vieja', 'Holstein', 'baja', 'H', 11, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'muerte', '2026-03-11', 0, 'parto complicado');
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('016', 'Perla', 'Normando', 'baja', 'H', 12, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'venta', '2026-02-20', 1800000, 'descarte por edad');
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('052', 'Nube', 'Gyrolando', 'baja', 'H', 6, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'perdida', '2026-01-06', 0, 'no apareció tras tormenta');
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('B-074M', 'Cría macho 058', 'Holstein × Gyr', 'baja', 'M', 0.1, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'venta', '2026-04-02', 900000, 'ternero macho');
INSERT INTO animales (id, nombre, raza, grupo, sexo, edad_anios, origen, del, partos, leche_ayer, estado_repro, prenez_meses, parto_estimado, ultima_palpacion, dias_vacia, lista_servicio, secar_estimado, retiro_leche_hasta, peso_kg, fecha_peso, ganancia_dia_g, destete_proximo, rol_toro, monta_natural, hijas_vivas, sanidad_al_dia, venta_programada, baja_motivo, baja_fecha, baja_valor, baja_nota) VALUES ('B-075', 'Cría de Paloma', 'Normando', 'baja', 'H', 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'muerte', '2026-04-20', 0, 'mortinato');

-- GENEALOGÍA (madre/padre)
UPDATE animales SET madre_id='017', padre_id='T01' WHERE id='042';
UPDATE animales SET madre_id='011', padre_id='T01' WHERE id='038';
UPDATE animales SET madre_id='033', padre_id='T01' WHERE id='051';
UPDATE animales SET madre_id='038', padre_id='T01' WHERE id='027';
UPDATE animales SET padre_id='T01' WHERE id='055';
UPDATE animales SET madre_id='042', padre_id='T01' WHERE id='064';
UPDATE animales SET madre_id='027', padre_id='T01' WHERE id='069';
UPDATE animales SET madre_id='019', padre_id='T01' WHERE id='071';
UPDATE animales SET madre_id='045', padre_id='T01' WHERE id='073';
UPDATE animales SET madre_id='058' WHERE id='B-074M';
UPDATE animales SET madre_id='033' WHERE id='B-075';

-- LECHEROS
INSERT INTO lecheros (id, nombre, frecuencia, dias_semana, base_litros) VALUES ('jose', 'Don José', 'diario', '{0,1,2,3,4,5,6}', 120);
INSERT INTO lecheros (id, nombre, frecuencia, dias_semana, base_litros) VALUES ('maria', 'Quesería La María', 'lmv', '{1,3,5}', 50);

-- TARIFA
INSERT INTO tarifa (precio_litro, moneda) VALUES (1950, 'COP');

-- POTREROS
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P1', 1, 12, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P2', 2, 19, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P3', 3, 26, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P4', 4, 33, FALSE, TRUE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P5', 5, 9, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P6', 6, 16, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P7', 7, -2, TRUE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P8', 8, 1, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P9', 9, 3, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P10', 10, 13, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P11', 11, 20, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P12', 12, 27, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P13', 13, 34, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P14', 14, 2, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P15', 15, 17, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P16', 16, 24, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P17', 17, 31, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P18', 18, 7, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P19', 19, 14, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P20', 20, 21, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P21', 21, 4, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P22', 22, 35, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P23', 23, 11, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P24', 24, 18, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P25', 25, 25, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P26', 26, 32, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P27', 27, 8, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P28', 28, 15, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P29', 29, 22, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P30', 30, 29, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P31', 31, 5, FALSE, FALSE);
INSERT INTO potreros (id, numero, dias_descanso, hato_actual, sugerido_siguiente) VALUES ('P32', 32, 12, FALSE, FALSE);

-- PRODUCCIÓN MENSUAL
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('042', '2026-03', 12.5);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('042', '2026-04', 14.8);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('042', '2026-05', 17.2);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('042', '2026-06', 18);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('038', '2026-01', 14.2);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('038', '2026-02', 14);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('038', '2026-03', 15.1);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('038', '2026-04', 14.8);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('038', '2026-05', 15.5);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('038', '2026-06', 16);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('051', '2026-03', 10.2);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('051', '2026-04', 12);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('051', '2026-05', 13.6);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('051', '2026-06', 14);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('027', '2026-05', 11.8);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('027', '2026-06', 13);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('017', '2026-01', 14);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('017', '2026-02', 13.5);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('017', '2026-03', 9);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('017', '2026-04', 10.5);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('017', '2026-05', 11);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('017', '2026-06', 11);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('033', '2026-01', 11);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('033', '2026-02', 10.2);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('033', '2026-03', 9.8);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('033', '2026-04', 8.5);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('033', '2026-05', 7);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('033', '2026-06', 6);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('029', '2026-01', 8);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('029', '2026-02', 7.5);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('029', '2026-03', 7);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('029', '2026-04', 6.2);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('029', '2026-05', 5.5);
INSERT INTO produccion_mensual (animal_id, mes, litros_dia) VALUES ('029', '2026-06', 5);

-- PARTOS
INSERT INTO partos (id, madre_id, cria_id, fecha, sexo_cria, peso_kg, tipo, estado_cria) VALUES ('P-2026-01', '042', '064', '2026-01-12', 'H', 36, 'normal', 'viva');
INSERT INTO partos (id, madre_id, cria_id, fecha, sexo_cria, peso_kg, tipo, estado_cria) VALUES ('P-2026-02', '027', '069', '2026-02-28', 'H', 34, 'normal', 'viva');
INSERT INTO partos (id, madre_id, cria_id, fecha, sexo_cria, peso_kg, tipo, estado_cria) VALUES ('P-2026-03', '033', 'B-075', '2026-04-20', 'H', 41, 'asistido', 'muerta');

-- TRATAMIENTOS
INSERT INTO tratamientos (id, animal_id, problema, medicamento, inicio, dias_retiro, retiro_leche_hasta, activo) VALUES ('T-017-01', '017', 'Mastitis', 'Antibiótico', '2026-06-10', 4, '2026-06-14', TRUE);
